name = "awsl-discord-bot"
main = "./src/server.js"
compatibility_date = "2023-12-01"
routes = [
	{ pattern = "discord-bot.awsl.icu", custom_domain = true }
]

[vars]
API_URL = "https://awsl.api.awsl.icu"
MOYU_URL = "https://moyu.awsl.icu/api/moyu_json"

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID

[ai]
binding = "AI"
